// console.log("2.for loop 0-50 odd no or even no")

// for(let i=1;i<=50;i++)
// {
//     if(i%2==0)
//     {
//         console.log(i," is even");
//     }
//     else{
//         console.log(i,"is odd");
//     }
// }


// console.log("3.reverse an array");
// console.log("");

// let a1=[1,2,3,4,5,6];
// let a2=[];


// for(i=a1.length;i>0;i--){
//     a2=i;
//     console.log(a2)
// }

console.log("4. print pattern-------------");

var n=prompt("enter a number");

for(var i=n;i>=1;i--){
  var star=""
  for(var j=1;j<=i;j++){
    star+="*"+" ";

  }
console.log(star);
}


// console.log("-----5. vowels count---")

// let vowels="aeiou"
// var input=prompt("enter a word");
// input=input.split("")
// vowels=vowels.split("");

// for(let i=0;i<=input.length;i++){
//   let vcount=0;
//   if(!vowels==input[i])
//   continue

//   vcount++;

//   console.log(vcount," vowels");
// }






// Problem - 1 solved

// let arr = [20,50,90,12,3]
// let big = arr[0]
// for (let i = 0; i < arr.length; i++) {
//     if(arr[i] > big){
//         big = arr[i]
//     }

// }
// console.log("Largest Number : ",big);











